config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "explore#index"

  devise_for :users

  # Routes for Explore page
  resources :explore

  #Routes for Posts
  resources :post do
    resources :comments, :likes
  end

  resources :dash_board

  #route for Search
  get "/search", to: "search#search"

  #route to user profile
  get "/profile/:username", to: "profile#show"

  #accept a candidate
  get "/post/:post_id/user/:user_id/accept", to: "application#accept"

  #reject a candidate
  get "/post/:post_id/user/:user_id/reject", to: "application#reject"

  #update post
  patch 'post/:id', to: 'post#update'

  #delete a comment
  post '/post/:id/comments/:comment_id', to: "comments#delete"
  
  #new Post
  post "/post/new", to: "post#create"

  #like post
  get "/post/:id/like", to: "post#like"

  #unlike post
  get "/post/:id/unlike", to: "post#unlike"

  #delete post
  get "/post/:id/delete", to: "post#destroy"

  #apply post
  get "/post/:id/apply", to: "post#apply"
  
  #Routes for Dashboard page
  get "/dash_board", to: "dash_board#index"

  #Route for Applications page
  get "/application", to: "application#index"

  #Route for Logout
  get "/logout", to: "logout#index"

end

app/controllers/dash_board_controller.rb
class DashBoardController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @profile = @user.profile
  end

  def edit
    if user_signed_in?
      @profile = current_user.profile
    end
  end

  def update
    @profile = Profile.find(current_user.profile.id)

    if @profile.update(profile_params)
        redirect_to "/dash_board"
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.find(current_user.id)
    @profile = @user.profile
    if @profile.image.attached?
      removeProfilePic()
      @profile.image.attach(params["@profile"]["image"])
    else
      @profile.image.attach(params["@profile"]["image"])
    end
    redirect_to "/dash_board"
  end

  private
    def profile_params
      params.require(:profile).permit(:profession, :contact_number, :state, :country, :link)
    end

    def removeProfilePic
      @user = User.find(current_user.id)
      @profile = @user.profile
      @profile.image.purge
      puts "Image Purged successfully"
    end
end

app/helpers/dash_board_helper.rb
module DashBoardHelper
    def get_notification_data()
        @notifications = []
        Post.all.map do |post|
            notification_data = Hash.new
            notification = get_notification(post)
            if !notification.nil? && notification.count != 0 && notification != []
                notification_data[:notification] = notification.first
                notification_data[:post] = post
                @notifications << notification_data
            end
        end
        if(@notifications.empty?) 
            []
        else 
            @notifications
        end
    end

    private
    def get_notification(post)
        nfs = []
        if user_signed_in?
            nfs = Notification.where(post_id: post.id, user_id: current_user.id)
        else
            nfs
        end
    end
end

app/views/dash_board/_form.html.erb
<%= stylesheet_link_tag 'dashboard.css' %>
<%= stylesheet_link_tag 'profile.css' %>

<div class="container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-3 mb-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                <%= form_for :@profile do |f| %>
                    <%= image_tag check_avatar(@profile), class: "dashb-profile-pic"%>
                    <div class="mt-3">
                        <h4><%= @user.f_name %> <%= @user.l_name %></h4>
                        <p class="text-secondary mb-1"><%= @profile.profession %></p>
                        <p class="text-muted font-size-sm"><%= @profile.state %>, <%= @profile.country %></p>
                    </div>
                    <%= f.file_field :image %>
                    <%= f.submit %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card mb-3">
            <div class="card-body">
              <button class="btn btn-primary"> <%= link_to "Edit", edit_dash_board_path(@profile), class: "edit-button" %></button>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Full Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @user.f_name %> <%= @user.l_name %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @user.email %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Profession</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @profile.profession %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Mobile</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @profile.contact_number %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Resume/CV link</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <a href=<%= @profile.link %>><%= @profile.link %></a>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0 heading">Address</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  <%= @profile.state %>, <%= @profile.country %>
                </div>
              </div>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/dash_board/edit.html.erb
<%= stylesheet_link_tag 'newPost.css' %>

<%= form_with model: @profile, url: dash_board_path(@profile), method: :patch, local: true do |f| %>
<h1>Hey <%= current_user.f_name %>, edit the details ?</h1>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>

  <div class="field">
    <%= f.label :resume_or_cv_link %><br>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.text_field :contact_number %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <div class="button">
    <%= f.submit %>
  </div>
<% end %>

app/views/dash_board/index.html.erb
<%= stylesheet_link_tag 'explore-main.css' %>

<%# Logo and Search Bar %>
<%= render '/common/header'%>

<%# Sidebar, Feed, Notifications %>
<div class="col-xs-12 content-container">
    <div class="col-xs-3 sidebar-container">
        <%= render '/common/sidebar'%>
    </div>
    <div class="col-xs-6 feed">
        <%= render 'dash_board/form' %>
    </div>
    <div class="col-xs-3">
        <%= render 'components/notifications/notification-tab'%>
    </div>
</div>